### ISSUE TITLE
There are cases where the expected results are not obtained.

### ISSUE THREAD

**Issue by pvcresin** [rskmoi/namedivider-python#1]
I don't think it can be divided perfectly in all cases, but I think it will be helpful for improvement.

|input|expected|result|
|-|-|-|
|中臣鎌足|中臣 鎌足|中 臣鎌足|
|豊臣秀吉|豊臣 秀吉|豊 臣秀吉|
|聖徳太子|聖徳 太子|聖 徳太子|

**Comment by rskmoi** [comment]
Thank you for sharing! 
Those names are not so common in modern Japan, so there is a lack of data to divide them.
I will update the kanji stats in a future release, but I think it will be a bit time consuming to deal with.

**Comment by rskmoi** [comment]
A new algorithm is introduced in today's v0.2.0 release: the class GBDTNameDivider can be used to achieve more accurate division.

中臣鎌足 and 豊臣秀吉 are now able to divide as expected.

```
$ nmdiv name 中臣鎌足 --mode gbdt
中臣 鎌足
$ nmdiv name 豊臣秀吉 --mode gbdt
豊臣 秀吉
```

Even with this algorithm, A still does not divide correctly.
```
$ nmdiv name 聖徳太子 --mode gbdt
聖 徳太子
```

However, since 聖徳太子 does not seem to be a name that can be divided into a family name and a given name, I will now close this ticket.
https://ja.wikipedia.org/wiki/%E8%81%96%E5%BE%B3%E5%A4%AA%E5%AD%90
